name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Version check
      run: rustc --version
      #run: cargo build --verbose
    - name: Build
      working-directory: test/assert_msg
      run: |
           cargo build --verbose
           #cargo run --verbose
    - name: Run tests
      working-directory: test/assert_msg
      run: |
           cargo test --verbose
